# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 345fc19d15392c81351eaee3e4f62fabe94440ca8ac0cb63a14740463f268f7d7b85a8ed85bab9bb18000e863203235a67d030e315c618c643f71834a8a06aa8

test:
  secret_key_base: 6e10ad472f87dda3d64ea782ddd138ee2436b9ac0a1c14e750ee16affe025790eb4ad44442e6df9a8f2c33d2206944563dd1e0927589b20e331088a98a5a4d97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
